name: WinCamStreamIOS
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "15.0"
targets:
  WinCamStreamIOS:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: App
        includes:
          - "**/*.swift"
          - "LaunchScreen.storyboard"
      - path: Core
    info:
      path: App/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        NSCameraUsageDescription: "Nous avons besoin de la caméra pour le streaming vidéo."
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationLandscapeLeft
        UIRequiresFullScreen: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.dashperf.wincamstreamios
      PRODUCT_NAME: WinCamStreamIOS
      INFOPLIST_FILE: App/Info.plist
      SWIFT_VERSION: 5.0
      CODE_SIGN_STYLE: Manual
      TARGETED_DEVICE_FAMILY: 1
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
