/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120856-g9893d66add-20250831"
#endif /* AVUTIL_FFVERSION_H */
